<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Donation;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class DonationController extends AdminBaseController
{

    public string $create = 'admin.users.donation_add';

    /**
     * İlgili controller model'i
     *
     * @var string
     */
    public string $model = Donation::class;

    /**
     * Anlık sayfa başlığı.
     *
     * @var string
     */
    public string $pageTitle = 'Bağışlar';

    /**
     * Tablo başlıkları
     *
     * @var array
     */
    public array $listTitle = [
        'Bağışı yapan kullanıcı' => [
            'user' => 'name'
        ],
        'Bağış miktarı' => 'money_count',
        'Şehir' => [
            'city' => 'sehir_title'
        ],
        'İlçe' => [
            'ilce' => 'ilce_title'
        ],
        'Mahalle' => [
            'district' => 'mahalle_title'
        ]
    ];

    /**
     * İlgili veri, tekil adı.
     *
     * @var string
     */
    public string $singularName = 'Bağış';

    /**
     * İlgili veri, çoklu adı.
     *
     * @var string
     */
    public string $pluralName = 'Bağışlar';

    /**
     * İlgili controller'in listeleme için route adı.
     *
     * @var string
     */
    public string $listRouteName = 'web.donation.index';

    /**
     * İlgili controller'in veri ekleme formu için route adı.
     *
     * @var string
     */
    public string $createRouteName = 'web.donation.create';

    /**
     * İlgili controller'in veri ekleme için route adı.
     *
     * @var string
     */
    public string $storeRouteName = 'web.donation.store';

    /**
     * İlgili controller'in veri güncelleme formu için route adı.
     *
     * @var string
     */
    public string $editRouteName = 'web.donation.edit';

    /**
     * İlgili controller'in veri güncelleme için route adı
     *
     * @var string
     */
    public string $updateRouteName = 'web.donation.update';

    /**
     * İlgili controller'in veri silme için route adı.
     *
     * @var string
     */
    public string $destroyRouteName = 'web.donation.destroy';

    /**
     * @var array|string[]
     */
    public array $with = [
        'user', 'city', 'ilce', 'district'
    ];

    /**
     * @var string
     */
    public string $tooltipName = 'ihbarı';

    /**
     * @var string
     */
    public string $tooltipTitle = 'name';

    public bool $canAdminAddData = true;

    public function setInputs(Model $model): void
    {
        $this->inputs = collect([]);
    }

    public function edit(int $id): Response
    {
        $data = $this->model::findOrFail($id);

        return \response()->view($this->create, [
            'postRoute' => route($this->updateRouteName, ['id' => $data->id]),
            'data' => $data,
            'method' => 'PUT'
        ]);
    }

    public function update(Request $request, int $id): RedirectResponse
    {
        return parent::update($request, $id); // TODO: Change the autogenerated stub
    }

}
